/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.pm3.teamretro;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class JumpAndBuildTest {
    @Test
    void appHasAGreeting() {
        // App classUnderTest = new App();
        assertNotNull("dummy");
    }
}
